// ─────────────────────────────────────────────────────────────────────────────
//  P R I M E    D E V  ·  Discord OAuth2 Auth-Link Server
// ─────────────────────────────────────────────────────────────────────────────

// Express server that handles the OAuth2 redirect from Discord after a
// member clicks the "Authenticate" button generated by /authlink.
//
// Flow:
//   1. /authlink (bot side) builds an authorize URL with scope
//      "identify guilds.join" and a one-time `state` token.
//   2. Member approves on Discord -> Discord redirects here:
//        GET {REDIRECT_URI}?code=...&state=...
//   3. We exchange `code` for an access token, fetch the user's profile
//      (id, username, avatar, banner), optionally join them to the guild
//      via PUT /guilds/{guild.id}/members/{user.id}, and persist everything
//      to database/system/auth-links.json.
//   4. We show a "Thanks for verifying!" page in their browser.
//
// NOTE: This does NOT run standalone. It's imported and started from the
// main index.js (see startAuthServer() call there), because this project's
// Pterodactyl egg only runs a single Node process / single startup command.
// Running it in-process also lets us read the real guild name straight off
// the live discord.js `client` instead of guessing it.

import express from 'express';
import { consumeState } from '../lib/managers/authState.js';
import { saveAuthLink } from '../lib/managers/authLinks.js';
import { getAuthRole } from '../lib/managers/authRole.js';
import { renderSuccessPage, renderErrorPage } from './pages/success.js';
import { buildVerificationThanksCard } from '../lib/builders/authCard.js';
import { BRAND, BRAND_LINK } from '../lib/constants.js';

/**
 * Starts the auth-link Express server.
 * @param {import('discord.js').Client} client the already-logged-in bot client,
 *   used to resolve the guild's real name for the success page.
 */
export function startAuthServer(client) {
  const {
    DISCORD_CLIENT_ID,
    DISCORD_CLIENT_SECRET,
    REDIRECT_URI,
    DISCORD_TOKEN,
    AUTH_SERVER_PORT,
    AUTO_JOIN_GUILD,
  } = process.env;

  if (!DISCORD_CLIENT_ID || !DISCORD_CLIENT_SECRET || !REDIRECT_URI) {
    console.warn('  [auth-server]  Skipped — missing DISCORD_CLIENT_ID / DISCORD_CLIENT_SECRET / REDIRECT_URI in .env');
    return;
  }

  const app = express();
  const PORT = AUTH_SERVER_PORT || 3000;

  app.get('/health', (_req, res) => res.status(200).send('ok'));

  app.get('/callback', async (req, res) => {
    const { code, state, error } = req.query;

    if (error) {
      return res.status(400).send(renderErrorPage(`Discord returned an error: ${error}`));
    }
    if (!code || !state) {
      return res.status(400).send(renderErrorPage('Missing authorization code or state — please request a fresh link.'));
    }

    // ── 1. Validate + consume the one-time state token ─────────────────────
    const stateEntry = consumeState(state);
    if (!stateEntry) {
      return res.status(400).send(renderErrorPage('This link is invalid or has expired. Please run /authlink again.'));
    }
    const { userId, guildId } = stateEntry;

    try {
      // ── 2. Exchange the code for an access token ──────────────────────────
      const tokenRes = await fetch('https://discord.com/api/oauth2/token', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        body: new URLSearchParams({
          client_id: DISCORD_CLIENT_ID,
          client_secret: DISCORD_CLIENT_SECRET,
          grant_type: 'authorization_code',
          code,
          redirect_uri: REDIRECT_URI,
        }),
      });

      if (!tokenRes.ok) {
        const errText = await tokenRes.text();
        console.error('[auth-server] token exchange failed:', errText);
        return res.status(400).send(renderErrorPage('Could not verify with Discord. Please try again.'));
      }

      const tokenData = await tokenRes.json();
      const { access_token, token_type } = tokenData;

      // ── 3. Fetch the member's Discord profile (avatar, banner, etc.) ──────
      const userRes = await fetch('https://discord.com/api/users/@me', {
        headers: { Authorization: `${token_type} ${access_token}` },
      });

      if (!userRes.ok) {
        console.error('[auth-server] failed to fetch user profile');
        return res.status(400).send(renderErrorPage('Could not fetch your Discord profile. Please try again.'));
      }

      const user = await userRes.json();

      const avatarURL = user.avatar
        ? `https://cdn.discordapp.com/avatars/${user.id}/${user.avatar}.${user.avatar.startsWith('a_') ? 'gif' : 'png'}?size=512`
        : `https://cdn.discordapp.com/embed/avatars/${Number(user.discriminator || 0) % 5}.png`;

      const bannerURL = user.banner
        ? `https://cdn.discordapp.com/banners/${user.id}/${user.banner}.${user.banner.startsWith('a_') ? 'gif' : 'png'}?size=1024`
        : null;

      // ── 4. (Optional) Auto-join the member into the guild ──────────────────
      let joined = false;
      if (AUTO_JOIN_GUILD === 'true' && DISCORD_TOKEN) {
        const joinRes = await fetch(
          `https://discord.com/api/guilds/${guildId}/members/${user.id}`,
          {
            method: 'PUT',
            headers: {
              Authorization: `Bot ${DISCORD_TOKEN}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ access_token }),
          },
        );
        joined = joinRes.ok || joinRes.status === 204;
        if (!joinRes.ok && joinRes.status !== 204) {
          console.error('[auth-server] guild join failed:', await joinRes.text());
        }
      }

      // ── 5. Persist the verified record ─────────────────────────────────────
      saveAuthLink(user.id, {
        username: `${user.username}${user.discriminator && user.discriminator !== '0' ? `#${user.discriminator}` : ''}`,
        avatar: user.avatar,
        avatarURL,
        banner: user.banner,
        bannerURL,
        guildId,
        joinedGuild: joined,
        accessToken: access_token,
        refreshToken: tokenData.refresh_token,
        revoked: false,
      });

      // ── 6. Resolve the real guild off the live client (falls back to a
      //      generic label if the bot isn't in that guild's cache yet) ───────
      const guild = client?.guilds?.cache?.get(guildId) ?? null;
      const guildName = guild?.name ?? 'the server';

      // ── 6b. (Optional) Auto-grant the configured verify role, if set via
      //       /verifyrole. Only attempted if the member is actually in the
      //       guild (either already, or just auto-joined in step 4) and the
      //       bot can resolve both the guild and the member.
      if (guild) {
        const roleId = getAuthRole(guildId);
        if (roleId) {
          const member = await guild.members.fetch(user.id).catch(() => null);
          if (member) {
            await member.roles.add(roleId).catch((err) => {
              console.error('[auth-server] role grant failed:', err.message);
            });
          }
        }
      }

      // ── 7. DM a "thanks for verifying" confirmation ─────────────────────────
      if (client) {
        try {
          const dmUser = await client.users.fetch(user.id);
          await dmUser.send(buildVerificationThanksCard(guild));
        } catch (dmErr) {
          console.warn(`[auth-server] could not DM ${user.id} (DMs likely closed) — skipping thanks message`);
        }
      }

      // ── 8. Show the success page ────────────────────────────────────────────
      return res.status(200).send(
        renderSuccessPage({
          username: user.username,
          guildName,
          brand: BRAND,
          brandLink: BRAND_LINK,
        }),
      );
    } catch (err) {
      console.error('[auth-server] unexpected error:', err);
      return res.status(500).send(renderErrorPage('Something went wrong on our end. Please try again shortly.'));
    }
  });

  app.listen(PORT, () => {
    console.log(`  [auth-server]  listening on port ${PORT}`);
    console.log(`  [auth-server]  callback endpoint: ${REDIRECT_URI}`);
  });
}
